title: double metric
description: Video game development blog

url: https://www.doublemetric.com
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    # github: francium-221
    twitter: francium_221
    # facebook: _
    # email: _
    # linkedin: _
    # youtube: _
    bluesky: mecha-fabs.bsky.social

google_analytics: "G-EKGZ942D35"

# disqus:
#    shortname: _
